# Generated by Django 5.2.4 on 2025-07-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSession',
            fields=[
                ('session_uid', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('track_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yarış Seansı',
                'verbose_name_plural': 'Yarış Seansları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField()),
                ('lap_time_ms', models.IntegerField()),
                ('start_time', models.FloatField(blank=True, null=True)),
                ('end_time', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='dashboard.racesession')),
            ],
            options={
                'ordering': ['lap_number'],
                'unique_together': {('session', 'lap_number')},
            },
        ),
        migrations.CreateModel(
            name='RawPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_id', models.IntegerField()),
                ('session_time', models.FloatField()),
                ('json_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_packets', to='dashboard.racesession')),
            ],
            options={
                'verbose_name': 'Ham UDP Paket',
                'verbose_name_plural': 'Ham UDP Paketleri',
                'ordering': ['session_time'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.FloatField()),
                ('lap_time', models.FloatField()),
                ('speed', models.IntegerField()),
                ('throttle', models.FloatField()),
                ('brake', models.FloatField()),
                ('gear', models.IntegerField(blank=True, null=True)),
                ('lap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='dashboard.lap')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='dashboard.racesession')),
            ],
            options={
                'ordering': ['session_time'],
            },
        ),
    ]
