# Generated by Django 5.2.4 on 2025-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrydata',
            name='fuel_in_tank',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
