# Generated by Django 5.2.4 on 2025-07-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_telemetrydata_fuel_in_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrydata',
            name='rpm',
            field=models.PositiveIntegerField(blank=True, help_text='Motor Devri (RPM)', null=True),
        ),
    ]
