# Generated by Django 5.2.4 on 2025-07-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_telemetrydata_rpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesession',
            name='session_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Bilinmiyor'), (1, 'Antrenman 1'), (2, 'Antrenman 2'), (3, 'Antrenman 3'), (4, 'Kısa Antrenman'), (5, 'Sıralama 1'), (6, 'Sıralama 2'), (7, 'Sıralama 3'), (8, 'Kısa Sıralama'), (9, 'Tek Turlu Sıralama'), (10, 'Yarış'), (11, 'Yarış 2'), (12, 'Zamana Karşı'), (13, 'Özel Grand Prix')], default=0, help_text='Seansın türü (Antrenman, Sıralama, Yarış vb.)', null=True),
        ),
    ]
