# Generated by Django 5.2.4 on 2025-07-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_racesession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesession',
            name='game_mode',
            field=models.IntegerField(blank=True, choices=[(0, 'Event Mode'), (3, 'Grand Prix'), (4, 'Grand Prix ‘23'), (5, 'Time Trial'), (6, 'Splitscreen'), (7, 'Online Custom'), (8, 'Online League'), (11, 'Career Invitational'), (12, 'Championship Invitational'), (13, 'Championship'), (14, 'Online Championship'), (15, 'Online Weekly Event'), (17, 'Story Mode'), (19, 'Career ‘22'), (20, 'Career ’22 Online'), (21, 'Career ‘23'), (22, 'Career ’23 Online'), (23, 'Driver Career ‘24'), (24, 'Career ’24 Online'), (25, 'My Team Career ‘24'), (26, 'Curated Career ‘24'), (127, 'Benchmark')], help_text='Oyun Modu (Kariyer, Online, GP vb.)', null=True),
        ),
        migrations.AlterField(
            model_name='racesession',
            name='session_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Bilinmiyor'), (1, 'Antrenman 1'), (2, 'Antrenman 2'), (3, 'Antrenman 3'), (4, 'Kısa Antrenman'), (5, 'Sıralama 1'), (6, 'Sıralama 2'), (7, 'Sıralama 3'), (8, 'Kısa Sıralama'), (9, 'Tek Turlu Sıralama'), (10, 'Sprint Shootout 1'), (11, 'Sprint Shootout 2'), (12, 'Sprint Shootout 3'), (13, 'Kısa Sprint Shootout'), (14, 'Tek Turlu Sprint Shootout'), (15, 'Yarış'), (16, 'Yarış 2'), (17, 'Yarış 3'), (18, 'Zamana Karşı')], default=0, help_text='Seansın türü (Antrenman, Sıralama, Yarış vb.)', null=True),
        ),
    ]
