# Generated by Django 5.2.4 on 2025-07-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_racesession_game_mode_alter_racesession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='tyre_compound',
            field=models.IntegerField(blank=True, choices=[(16, 'Soft'), (17, 'Medium'), (18, 'Hard'), (7, 'Inter'), (8, 'Wet'), (19, 'F2 Super Soft'), (20, 'F2 Soft'), (21, 'F2 Medium'), (22, 'F2 Hard')], help_text='Tur sırasında kullanılan görsel lastik bileşiği', null=True),
        ),
    ]
