# Generated by Django 5.2.4 on 2025-07-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_lap_tyre_compound'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrydata',
            name='drs',
            field=models.BooleanField(default=False, help_text='DRS durumu (0=kapalı, 1=açık)'),
        ),
        migrations.AddField(
            model_name='telemetrydata',
            name='ers_deploy_mode',
            field=models.IntegerField(blank=True, help_text='ERS kullanım modu (0=yok, 1=medium, 2=hotlap, 3=overtake)', null=True),
        ),
        migrations.AddField(
            model_name='telemetrydata',
            name='ers_store_energy',
            field=models.FloatField(blank=True, help_text='ERS bataryasında depolanan enerji (Joule)', null=True),
        ),
    ]
